name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  update-leetcode-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fetch LeetCode Stats
        run: |
          curl -s https://leetcode-stats-api.herokuapp.com/Conquistador17 > leetcode_stats.json

      - name: Extract Stats and Update README
        run: |
          solved=$(cat leetcode_stats.json | jq .totalSolved)
          contributions=$(cat leetcode_stats.json | jq .contributionPoints)
          upvotes=$(cat leetcode_stats.json | jq .totalUpvotes)

          # Update README.md with the fetched stats
          sed -i "s/LeetCode Solved:.*$/LeetCode Solved: ${solved}/" README.md
          sed -i "s/LeetCode Contributions:.*$/LeetCode Contributions: ${contributions}/" README.md
          sed -i "s/LeetCode Upvotes:.*$/LeetCode Upvotes: ${upvotes}/" README.md

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update LeetCode stats"
          git push origin main
