name: Update LeetCode Streak

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  update-leetcode-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fetch LeetCode Profile Calendar
        run: |
          curl -s https://leetcode.com/graphql/ \
            -H "Content-Type: application/json" \
            -d '{"operationName":"userProfileCalendar","query":"query userProfileCalendar($username: String!, $year: Int) { matchedUser(username: $username) { userCalendar(year: $year) { activeYears streak totalActiveDays dccBadges { timestamp badge { name icon } } submissionCalendar } } }","variables":{"username":"Conquistador17"}}' > profile_data.json

      - name: Validate JSON
        run: |
          if ! jq -e . >/dev/null 2>&1 <<<$(cat profile_data.json); then
            echo "Failed to fetch or parse the profile data"
            exit 1
          fi

      - name: Update README
        run: |
          streak=$(jq .data.matchedUser.userCalendar.streak profile_data.json)
          totalActiveDays=$(jq .data.matchedUser.userCalendar.totalActiveDays profile_data.json)

          # Update README.md with profile calendar data
          sed -i "s/LeetCode Streak:.*$/LeetCode Streak: ${streak}/" README.md
          sed -i "s/Total Active Days:.*$/Total Active Days: ${totalActiveDays}/" README.md

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md profile_data.json
          git commit -m "Update LeetCode profile calendar stats"
          git push origin main
