name: Update LeetCode Stats and Streak

on:
  schedule:
    - cron: '0 0 * * *' # Run every hour
  workflow_dispatch:

jobs:
  update-leetcode-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 1: Fetch LeetCode Profile Calendar (for streak and total active days)
      - name: Fetch LeetCode Profile Calendar
        run: |
          curl -s https://leetcode.com/graphql/ \
            -H "Content-Type: application/json" \
            -d '{"operationName":"userProfileCalendar","query":"query userProfileCalendar($username: String!, $year: Int) { matchedUser(username: $username) { userCalendar(year: $year) { streak totalActiveDays } } }","variables":{"username":"Conquistador17"}}' > profile_calendar_data.json

      - name: Output profile calendar data (for debugging)
        run: |
          cat profile_calendar_data.json

      - name: Validate profile calendar JSON
        run: |
          if ! jq -e . >/dev/null 2>&1 <<<$(cat profile_calendar_data.json); then
            echo "Failed to fetch or parse the profile calendar data"
            exit 1
          fi

      # Step 2: Fetch LeetCode Public Profile (for postViewCount, postViewCountDiff, and reputation)
      - name: Fetch LeetCode Public Profile
        run: |
          curl -s https://leetcode.com/graphql/ \
            -H "Content-Type: application/json" \
            -d '{"operationName":"userPublicProfile","query":"query userPublicProfile($username: String!) { matchedUser(username: $username) { profile { postViewCount postViewCountDiff reputation } } }","variables":{"username":"Conquistador17"}}' > profile_stats_data.json

      - name: Output profile stats data (for debugging)
        run: |
          cat profile_stats_data.json

      - name: Validate profile stats JSON
        run: |
          if ! jq -e . >/dev/null 2>&1 <<<$(cat profile_stats_data.json); then
            echo "Failed to fetch or parse the profile stats data"
            exit 1
          fi

      # Step 3: Update README with streak, total active days, post view count, and reputation
      - name: Update README
        run: |
          # Extract values from profile calendar data
          streak=$(jq .data.matchedUser.userCalendar.streak profile_calendar_data.json)
          totalActiveDays=$(jq .data.matchedUser.userCalendar.totalActiveDays profile_calendar_data.json)

          # Extract values from profile stats data
          postViewCount=$(jq .data.matchedUser.profile.postViewCount profile_stats_data.json)
          postViewCountDiff=$(jq .data.matchedUser.profile.postViewCountDiff profile_stats_data.json)
          reputation=$(jq .data.matchedUser.profile.reputation profile_stats_data.json)

          echo "Streak: $streak"
          echo "Total Active Days: $totalActiveDays"
          echo "Post View Count: $postViewCount"
          echo "Post View Count Difference: $postViewCountDiff"
          echo "Reputation: $reputation"

          # Update README.md with both profile calendar and public profile data
          sed -i "s/LeetCode Streak:.*$/LeetCode Streak: ${streak}/" README.md
          sed -i "s/Total Active Days:.*$/Total Active Days: ${totalActiveDays}/" README.md
          sed -i "s/Post View Count:.*$/Post View Count: ${postViewCount}/" README.md
          sed -i "s/Post View Count Difference:.*$/Post View Count Difference: ${postViewCountDiff}/" README.md
          sed -i "s/Reputation:.*$/Reputation: ${reputation}/" README.md

      # Step 4: Commit and push the changes
      - name: Commit changes
        run: |
          git config --global user.email "a@example.com"
          git config --global user.name "a"
          git add README.md profile_calendar_data.json profile_stats_data.json
          git commit -m "Update LeetCode profile calendar and stats"
          git push origin main
