name: Update LeetCode Streak

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  update-leetcode-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fetch LeetCode Streak
        run: |
          curl -s https://leetcode.com/graphql/ \
            -H "Content-Type: application/json" \
            -d '{"query": "query getStreakCounter { streakCounter { streakCount daysSkipped currentDayCompleted }}"}' > streak_data.json

      - name: Validate JSON
        run: |
          if ! jq -e . >/dev/null 2>&1 <<<$(cat streak_data.json); then
            echo "Failed to fetch or parse the streak data"
            exit 1
          fi

      - name: Update README
        run: |
          streakCount=$(jq .data.streakCounter.streakCount streak_data.json)
          daysSkipped=$(jq .data.streakCounter.daysSkipped streak_data.json)
          currentDayCompleted=$(jq .data.streakCounter.currentDayCompleted streak_data.json)

          # Update README.md with streak data
          sed -i "s/LeetCode Streak:.*$/LeetCode Streak: ${streakCount}/" README.md
          sed -i "s/Days Skipped:.*$/Days Skipped: ${daysSkipped}/" README.md
          sed -i "s/Current Day Completed:.*$/Current Day Completed: ${currentDayCompleted}/" README.md

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md streak_data.json # Add both README.md and streak_data.json
          git commit -m "Update LeetCode streak stats"
          git push origin main
